# fly.toml app configuration file generated for google-form on 2024-02-13T18:18:40+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'google-form'
primary_region = 'sin'

[env]
  PORT = 3000
  SHOPIFY_APP_URL = "https://google-form.fly.dev"
  SHOPIFY_API_KEY = "f5e3edcc96ca660b4d4b56250a493c61"
  SCOPES = "write_products"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
